spring:
  kafka:
    bootstrap-servers: 192.168.1.113:9092
    consumer:
      bootstrap-servers: 192.168.1.113:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 192.168.1.113:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
# Circuit Braker
resilience4j:
    circuitbreaker:
        instances:
            mockService:
                slidingWindowSize: 3
                slidingWindowType: COUNT_BASED
                #waitDurationInOpenState: 5
                wait-duration-in-open-state: 5
                #waitInterval: 10000
                failureRateThreshold: 50
                permittedNumberOfCallsInHalfOpenState: 5
                registerHealthIndicator: true
                #register-health-indicator: true
                allowHealthIndicatorToFail: true
        configs:
            default:
                registerHealthIndicator: true

management.health.circuitbreakers.enabled: true
management:
  endpoint:
    health:
        show-details: always